# Generated by Django 4.2.3 on 2025-06-20 07:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_id", models.UUIDField(default=uuid.uuid4, unique=True, verbose_name="세션 ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
            ],
            options={
                "verbose_name": "채팅 세션",
                "verbose_name_plural": "채팅 세션들",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_message", models.TextField(verbose_name="사용자 메시지")),
                ("bot_response", models.TextField(verbose_name="봇 응답")),
                ("sources", models.JSONField(blank=True, default=list, verbose_name="참조 문서들")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일")),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="chat_bot.chatsession"
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 메시지",
                "verbose_name_plural": "채팅 메시지들",
                "ordering": ["created_at"],
            },
        ),
    ]
