# Generated by Django 4.2.3 on 2025-06-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="내용")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("company", "회사 소개"),
                            ("service", "서비스/제품"),
                            ("faq", "FAQ"),
                            ("policy", "정책"),
                            ("tech", "기술 문서"),
                        ],
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
            ],
            options={
                "verbose_name": "KnowledgeDocument",
                "verbose_name_plural": "KnowledgeDocument",
                "db_table": "knowledge_document",
                "ordering": ["-created_at"],
            },
        ),
    ]
