# Generated by Django 4.2.3 on 2025-06-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge_document", "0002_blogpost_category_chatlog_chromavector_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="url",
            field=models.URLField(max_length=500, unique=True, verbose_name="블로그 URL"),
        ),
    ]
